Add notes on ROS2 approaches and add actions
microROS/design pull request #5
Opened 2018-10-20 19:58 UTC by BorjaOuterelo

Expands Robotis projects approach regarding MW and protocol used.
Adds MW actions related to current OFERA work.

2018-10-22 06:54 UTC, richiware submitted a review, later dismissed

2018-10-22 06:58 UTC, ralph-lange submitted a review, later dismissed

2018-10-22 07:02 UTC, iluetkeb commented on articles/embedded.md
> +| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFE
```suggestion
| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFERA and ROBOTIS have demonstrated that it is a suitable protocol to seamlessly communicate with microcontrollers. | [DDS-XRCE](https://www.omg.org/spec/DDS-XRCE/) |
```

2018-10-22 07:09 UTC, iluetkeb requested changes
I like the additions. A few grammatical changes are suggested.

One note that I would like a comment on is the use of the micro-ros.com domain. I thought we had decided to use the Github IO page only. I may be wrong, of course, please clarify.

2018-10-22 07:09 UTC, iluetkeb commented on articles/embedded.md
> +| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFE
```suggestion
| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFERA and ROBOTIS have demonstrated that it is a suitable protocol to seamlessly communicate with microcontrollers. | [DDS-XRCE](https://www.omg.org/spec/DDS-XRCE/) |
```

2018-10-22 07:09 UTC, iluetkeb commented on articles/embedded.md
> +| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFE
```suggestion
| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFERA and ROBOTIS have demonstrated that it is a suitable protocol to seamlessly communicate with microcontrollers. | [DDS-XRCE](https://www.omg.org/spec/DDS-XRCE/) |
```

2018-10-22 07:09 UTC, iluetkeb commented on articles/embedded.md
> +| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFE
I found "proved", with its connotation of formality a bit too strong. "demonstrate" should suffice.

2018-10-22 07:09 UTC, iluetkeb commented on articles/embedded.md
> +*   [EU project OFERA](http://ofera.eu/): The EU project OFERA (Open Framework for Embedded Robot Applications) aims at a ROS 2-compatible stack for MCUs in the range of STM32F4 or STM32L1, i.e. with
Have you guys reached a consensus on the use of the domains with Erle? Personally, I would prefer linking to the Github-page for micro-ROS only.

2018-10-22 07:09 UTC, iluetkeb commented on articles/embedded.md
> +*   [EU project OFERA](http://ofera.eu/): The EU project OFERA (Open Framework for Embedded Robot Applications) aims at a ROS 2-compatible stack for MCUs in the range of STM32F4 or STM32L1, i.e. with
```suggestion
*   [EU project OFERA](http://ofera.eu/): The EU project OFERA (Open Framework for Embedded Robot Applications) aims at a ROS 2-compatible stack for MCUs in the range of STM32F4 or STM32L1, i.e. with possibly less than 100kB RAM. The project partners currently investigate of using the ROS 2 rmw, rcl and rclcpp layers as-is on the Micro XRCE-DDS implementation of the upcoming DDS-XRCE standard. In parallel, a more modular approach in the style of rosserial is investigated. In the project's use-cases, NuttX is considered as primary choice for the RTOS. Beyond the project page, additional details of the project results can be found at [https://microros.github.io/micro-ROS/](https://microros.github.io/micro-ROS/).
```
```suggestion
*   [EU project OFERA](http://ofera.eu/): The EU project OFERA (Open Framework for Embedded Robot Applications) aims at a ROS 2-compatible stack for MCUs in the range of STM32F4 or STM32L1, i.e. with possibly less than 100kB RAM. The project partners currently investigate of using the ROS 2 rmw, rcl and rclcpp layers as-is on the Micro XRCE-DDS implementation of the upcoming DDS-XRCE standard. In parallel, a more modular approach in the style of rosserial is investigated. In the project's use-cases, NuttX is considered as primary choice for the RTOS. Beyond the project page, additional details of the project results can be found at [http://micro-ros.com](http://micro-ros.com).
```

2018-10-22 07:09 UTC, iluetkeb commented on articles/embedded.md
> +*   [EU project OFERA](http://ofera.eu/): The EU project OFERA (Open Framework for Embedded Robot Applications) aims at a ROS 2-compatible stack for MCUs in the range of STM32F4 or STM32L1, i.e. with
```suggestion
*   [EU project OFERA](http://ofera.eu/): The EU project OFERA (Open Framework for Embedded Robot Applications) aims at a ROS 2-compatible stack for MCUs in the range of STM32F4 or STM32L1, i.e. with possibly less than 100kB RAM. The project partners currently investigate of using the ROS 2 rmw, rcl and rclcpp layers as-is on the Micro XRCE-DDS implementation of the upcoming DDS-XRCE standard. In parallel, a more modular approach in the style of rosserial is investigated. In the project's use-cases, NuttX is considered as primary choice for the RTOS. Beyond the project page, additional details of the project results can be found at [https://microros.github.io/micro-ROS/](https://microros.github.io/micro-ROS/).
```

2018-10-22 07:09 UTC, iluetkeb commented on articles/embedded.md
> +  Project enabling communication between Robotis' OpenCR board and ROS 2 nodes as part of the TurtleBot3 platform. This communication is enabled using DDS-XRCE implementation, Micro XRCE-DDS.
```suggestion
  Project enabling communication between Robotis' OpenCR board and ROS 2 nodes as part of the TurtleBot3 platform. This communication is enabled using a DDS-XRCE implementation, Micro XRCE-DDS.
```

2018-10-22 07:14 UTC, iluetkeb commented on articles/embedded.md
> +| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFE
```suggestion
| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFERA and ROBOTIS have demonstrated that it is a suitable protocol to communicate with microcontrollers. | [DDS-XRCE](https://www.omg.org/spec/DDS-XRCE/) |
```

2018-10-22 07:16 UTC, iluetkeb commented on articles/embedded.md
> +| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFE
```suggestion
| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFERA and ROBOTIS have demonstrated that it is a suitable protocol to communicate with microcontrollers. | [DDS-XRCE](https://www.omg.org/spec/DDS-XRCE/) |
```

2018-10-22 07:16 UTC, iluetkeb commented on articles/embedded.md
> +| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFE
```suggestion
| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFERA and ROBOTIS have demonstrated that it is a suitable protocol to communicate with microcontrollers. | [DDS-XRCE](https://www.omg.org/spec/DDS-XRCE/) |
```

2018-10-22 07:16 UTC, iluetkeb commented on articles/embedded.md
> +| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFE
"proved" sounds very formal. Maybe write "demonstrate" instead. Also "seamless" -> "seamlessly".

btw, I tried adding a commit but it didn't work.

2018-10-22 07:28 UTC, iluetkeb commented on articles/embedded.md
> +| A-DDS-XRCE | Q-MIDDLEWARE | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFE
"proved" sounds very formal. Maybe write "demonstrate" instead. Also "seamless" -> "seamlessly".

btw, I tried adding a commit but it didn't work.

2018-10-22 11:16 UTC, iluetkeb commented on articles/embedded.md
> +*   [EU project OFERA](http://ofera.eu/): The EU project OFERA (Open Framework for Embedded Robot Applications) aims at a ROS 2-compatible stack for MCUs in the range of STM32F4 or STM32L1, i.e. with
```suggestion
*   [EU project OFERA](http://ofera.eu/): The EU project OFERA (Open Framework for Embedded Robot Applications) aims at a ROS 2-compatible stack for MCUs in the range of STM32F4 or STM32L1, i.e. with possibly less than 100kB RAM. The project partners currently investigate of using the ROS 2 rmw, rcl and rclcpp layers as-is on the Micro XRCE-DDS implementation of the upcoming DDS-XRCE standard. In parallel, a more modular approach in the style of rosserial is investigated. In the project's use-cases, NuttX is considered as primary choice for the RTOS. Beyond the project page, additional details of the project results can be found at [https://microros.github.io/micro-ROS/](https://microros.github.io/micro-ROS/).
```

2018-10-23 07:13 UTC, BorjaOuterelo commented on articles/embedded.md
> +*   [EU project OFERA](http://ofera.eu/): The EU project OFERA (Open Framework for Embedded Robot Applications) aims at a ROS 2-compatible stack for MCUs in the range of STM32F4 or STM32L1, i.e. with
Yes, we agreed to use Github provided domain https://microros.github.io/micro-ROS/

2018-10-23 08:05 UTC, vmayoral submitted a review, later dismissed

2018-10-23 08:36 UTC, ralph-lange commented on articles/embedded.md
> +| A-DDS-XRCE | Q-COMM | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFERA and
Is the order DDS XRCE correct? I.e. the standard is named DDS XRCE whereas your implementation is named Micro XRCE-DDS?

2018-10-23 10:27 UTC, BorjaOuterelo commented on articles/embedded.md
> +| A-DDS-XRCE | Q-COMM | Use of DDS-XRCE standard protocol | This OMG standard defines the protocol used by microcontrollers to publish and subscribe data to a DDS Domain, standard in ROS 2. OFERA and
Hi @ralph-lange. Yes, that's correct. OMG standard acronym is DDS-XRCE, and eProsima's product name is Micro XRCE-DDS.

2018-10-23 12:09 UTC, BorjaOuterelo commented
@iluetkeb I have addressed your observations.

2018-10-24 07:23 UTC, iluetkeb submitted a review, later dismissed

2018-10-24 07:23 UTC, ralph-lange submitted a review, later dismissed

2018-10-24 07:23 UTC, ralph-lange commented on articles/embedded.md
> +*   [Renesas GR-ROSE](http://gadget.renesas.com/ja/event/2018/pm_rose.html):
Renesas GR-ROSE in bold, please.

2018-10-24 07:23 UTC, ralph-lange commented on articles/embedded.md
> +*   [XEL Network by ROBOTIS](https://xelnetwork.readthedocs.io):
XEL Network by Robotis in bold, please, for consistency.

2018-10-24 07:28 UTC, BorjaOuterelo commented on articles/embedded.md
> +*   [Renesas GR-ROSE](http://gadget.renesas.com/ja/event/2018/pm_rose.html):
Done

2018-10-24 07:28 UTC, BorjaOuterelo commented on articles/embedded.md
> +*   [XEL Network by ROBOTIS](https://xelnetwork.readthedocs.io):
Done

2018-10-24 07:35 UTC, BorjaOuterelo commented
@iluetkeb @ralph-lange I pushed latest changes following your recommendations. Can you check and we merge this before the ROS 2 PR?.

2018-10-24 09:20 UTC, iluetkeb approved these changes

2018-10-24 09:24 UTC, vmayoral approved these changes

2018-10-24 09:28 UTC, merged